name: Release Announcement
on:
  release:
    types: [published, prereleased]
jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-latest
    outputs:
      release_data: ${{steps.step1.outputs.release_data}}
    steps:
    - id: step1
      name: Release Fetcher
      uses: hugoalh/GitHubAction.ReleaseFetcher@0.1.0
  send_to_discord:
    name: Send To Discord
    runs-on: ubuntu-latest
    needs: [fetch]
    steps:
      - id: step2
        uses: hugoalh/GitHubAction.SendToDiscord@0.1.0
        with:
          discord_webhook_url: ${{secrets.DISCORD_WEBHOOK_URL}}
          message_text: "[Minecraft Java Data Pack] Tag+ %Release.Version% is now available on GitHub (%Release.WebUrl%).\n\n%Note_Split.1%"
          message_variables_list: ${{needs.fetch.outputs.release_data}}
