name: "Release Announcement"
on:
  release:
    types:
    - "published"
jobs:
  fetch-data:
    name: "Fetch Data"
    runs-on: "ubuntu-latest"
    outputs:
      release_data: "${{steps.main.outputs.release_data}}"
    steps:
    - id: "setup-nodejs"
      name: "Setup NodeJS"
      uses: "actions/setup-node@v1"
      with:
        node-version: "12"
    - id: "setup-nodejs-dependencies"
      name: "Setup NodeJS Dependencies"
      run: npm install
    - id: "main"
      uses: "hugoalh/GitHubAction.ReleaseFetcher@v0"
  send-to-discord:
    name: "Send To Discord"
    runs-on: "ubuntu-latest"
    needs: 
    - "fetch-data"
    steps:
    - id: "setup-nodejs"
      name: "Setup NodeJS"
      uses: "actions/setup-node@v1"
      with:
        node-version: "12"
    - id: "setup-nodejs-dependencies"
      name: "Setup NodeJS Dependencies"
      run: npm install
    - id: "main"
      uses: "hugoalh/GitHubAction.SendToDiscord@v0"
      with:
        discord_webhook_url: ${{secrets.DISCORD_WEBHOOK_URL}}
        message_text: "[Minecraft Java Data Pack] Tag+ %Release.Version% is now available on GitHub (%Release.WebUrl%).\n\n%Note_Split.1%"
        message_variables_list: ${{needs.fetch.outputs.release_data}}
